# folder settings
source: .
destination: ./_site

# site settings
permalink: /:categories/:title
markdown: rdiscount

# custom vars
url: sparanoid.com
file: http://a1.sparanoid.com
assets: /assets
name: Sparanoid
full-name: Tunghiao Liu
email: info@sparanoid.com
twitter: sparanoid
slogan: The net is vast and limitless
googe-custom-search: 012621050422714259885:jabcs0nmacy

# fire up a localhost and auto generate when files change
auto: true
server: ture
server_port: 4321

# exclude files for generated site
exclude: 
- README.md
- LICENSE
#- a.css
- Rakefile